/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// Core types for AI Resume Screening Agent

export interface ParsedJobDescription {
  title: string;
  requiredSkills: string[];
  preferredSkills: string[];
  responsibilities: string[];
  minimumExperience: number; // in years
  educationRequirement: string;
  keywords: string[];
  technologies: string[];
  softSkills: string[];
}

export interface JobDescription {
  id: string;
  title: string;
  rawText: string;
  parsedData: ParsedJobDescription;
  createdAt: string;
}

export interface CandidateEducation {
  degree: string;
  university: string;
  gradYear?: string;
  cgpa?: string;
}

export interface CandidateExperience {
  role: string;
  company: string;
  duration?: string;
  description?: string;
}

export interface CandidateProject {
  title: string;
  description?: string;
  technologies?: string[];
}

export interface ParsedResume {
  name: string;
  email: string;
  phone: string;
  linkedin: string;
  github: string;
  portfolio: string;
  location: string;
  skills: string[];
  projects: CandidateProject[];
  experience: CandidateExperience[];
  totalExperienceYears: number;
  education: CandidateEducation[];
  certifications: string[];
  achievements: string[];
  languages: string[];
}

export interface Candidate {
  id: string;
  name: string;
  email: string;
  phone: string;
  filename: string;
  rawText: string;
  parsedData: ParsedResume;
  createdAt: string;
}

export interface ScreeningResult {
  id: string;
  candidateId: string;
  jdId: string;
  overallScore: number;
  semanticScore: number;
  skillScore: number;
  experienceScore: number;
  educationScore: number;
  bonusScore: number;
  matchedSkills: string[];
  missingSkills: string[];
  additionalSkills: string[];
  aiExplanation: string; // Detail generated by Gemini
  hiringRecommendation: "Strong Hire" | "Hire" | "Potential" | "No Match";
  screenedAt: string;
}

export interface ScreeningDetails extends ScreeningResult {
  candidate: Candidate;
  jobDescription: JobDescription;
}

export interface DashboardStats {
  totalCandidates: number;
  averageScore: number;
  strongHiresCount: number;
  skillsFrequency: Record<string, number>;
}
